language: c
before_install:
  - sudo apt-get update  -qq
  - sudo apt-get install -yq build-essential linux-headers-generic g++-multilib gcc-multilib
#  - sudo apt-get install -qq clang
#  - sudo apt-get install -qq valgrind
install: true
script: make WITH_FAST_SYSCALL=1 && make WITH_FAST_SYSCALL=1 test
